# ---------------------------------------------------------
# Blog infos
# ---------------------------------------------------------
name: 5pani2pesci
subname: Aventuras de la providencia diarias
description: 5p2p en español
metadata: [matrimonio, cristiano, amor]
url: http://5p2p.es
about: /sobre-nosotros
language: es

# ---------------------------------------------------------
# Devel --# comment on production phase!
# ---------------------------------------------------------
# baseurl: /5p2p.es

# ---------------------------------------------------------
# Blog basic design
# ---------------------------------------------------------
logo:    /images/logo/logo-5p2p-256.png
favicon: /images/logo/logo-5p2p-64.png
header:  /images/header/header.png # landing page header
fb_img:  /images/header/header.png # default post header

# ---------------------------------------------------------
# Authors
# ---------------------------------------------------------
authors:

    - name: ruvido
      display: Francesco

    - name: alescanca
      display: Alessandra

    - name: guest
      display: Guest # da cambiare!!

# ---------------------------------------------------------
# Menus
# ---------------------------------------------------------
menu:

  - title: "Blog"
    href: "/blog"
    class: 

 - title: "Sobre nosostros"
    href: "/sobre-nosotros"

  - title: "Escríbanos"
    href: "https://www.facebook.com/es5p2p"
    # href: "/escribanos"

  - title: "Facebook"
    href: "https://www.facebook.com/es5p2p"

  # - title: "Cursos"
  #   href: "/cursos"
  #   class: 

  # - title: "Libros"
  #   href: "/libros"
  #   class: 

  # - title: "Bodas"
  #   href: "http://weddings.5p2p.it"
  #   class: 

  # - title: "Donaciones"
  #   href: "/donaciones"
  #   class: donations

  # - title: "Scrivici"
  #   href: "/scrivici"


  # - title: "Corsi"
  #   href: "/corsi"

  # - title: "Fotografia de Bodas"
  #   href: "/bodas"
# ---------------------------------------------------------
footer_menu:

  - title: "Sobre nosostros"
    href: "/sobre-nosotros"

  - title: "Escríbanos"
    href: "/escribanos"

  - title: "Facebook"
    href: "https://www.facebook.com/es5p2p" # controlla!

# ---------------------------------------------------------
# Accounts
# ---------------------------------------------------------
google_analytics: UA-69446168-1

# ---------------------------------------------------------
# Jekyll stuff
# ---------------------------------------------------------
assets: /assets/
images: /images/posts
previews: /previews
permalink: /:categories/:title/
# permalink: pretty
markdown: kramdown
timezone: Europe/Rome
future: false
sass:
  # style: compressed
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      author: "guest"
